version: '3.3'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: 'my-house-video-player/server:latest'
    ports:
      - '8081:8081'
    stdin_open: true
    tty: true
